#!/bin/bash

. ~/MVNEnv/defineColors.sh

MSG_INFO="${SCRIPT_OUTPUT_PREFIX}${CYELLOW}INFO:${CEND}  "
MSG_ERROR="${SCRIPT_OUTPUT_PREFIX}${CRED}ERROR:${CEND} "
MSG_QUESTION="${SCRIPT_OUTPUT_PREFIX}${CGREEN}QSTN:${CEND}  "

