#!/bin/bash

export MSG_INFO="${SCRIPT_OUTPUT_PREFIX}${CYELLOW}INFO:${CEND}  "
export MSG_ERROR="${SCRIPT_OUTPUT_PREFIX}${CRED}ERROR:${CEND} "
export MSG_QUESTION="${SCRIPT_OUTPUT_PREFIX}${CGREEN}QSTN:${CEND}  "

