#!/bin/bash

. ~/Scripts/defineColors.sh

WRK_DIR=${PROJ_BASE_DIR}
DST_DIR=~/cscope/indexes/${PROJ_NAME}
NAME_FILE=cscope.files
PATTERNS='-name "*.[ch]" -o -name "*.cpp" -o -name "*.hpp" -o -name "*.java"'
INDEX_FILE=cscope.out
EXTRA_OPTS="-Rq"

function showHelp {
	echo "Generate a cscope index file for a given working directory."
	echo "Syntax: $0 <options>"
	echo
	echo "Options:"
	echo "    -h	Show this help."
	echo "    -w	Specify the working directory."
	echo "          Defaults to ~/workspace/BO_embratel-dsti74.zapper-rev1_trunk/."
	echo "    -d	Specify the destination directory (where files will be generated)."
	echo "          Defaults to ~/scope/."
	echo "    -n	Specify the name file (to be used by cscope)."
	echo "          Defaults to cscope.files."
	echo "    -p	Specify the finding pattern."
	echo "          Defaults to -name \"*.[ch]\" -o -name \"*.cpp\" -o -name \"*.hpp\" -o -name \"*.java\"."
	echo "    -i	Specify the index file (to be generated by cscope)."
	echo "          Defaults to cscope.out."
	echo "    -e	Specify extra parameters to be passed to cscope."
	echo "          Defaults to none."
	echo "    -v	Verbose output (including errors when running cscope)."
	echo
	exit 0;
}

while getopts w:d:n:p:i:e:hv option; do
        case "${option}" in
		h) showHelp;;
                w) WRK_DIR=${OPTARG};;
                d) DST_DIR=${OPTARG};;
                n) NAME_FILE=${OPTARG};;
		p) PATTERNS=${OPTARG};;
		i) INDEX_FILE=${OPTARG};;
		e) EXTRA_OPTS=${OPTARG};;
		v) VERBOSE=1;;
        esac
done

echo -e "${CCYAN}WORK DIRECTORY:        ${CYELLOW}${WRK_DIR}${CEND}"
echo -e "${CCYAN}DESTINATION DIRECTORY: ${CYELLOW}${DST_DIR}${CEND}"
echo -e "${CCYAN}NAME FILE:             ${CYELLOW}${NAME_FILE}${CEND}"
echo -e "${CCYAN}PATTERNS:              ${CYELLOW}${PATTERNS}${CEND}"
echo -e "${CCYAN}SCOPE INDEX FILE:      ${CYELLOW}${INDEX_FILE}${CEND}"
echo -e "${CCYAN}SCOPE EXTRA OPTIONS:   ${CYELLOW}${EXTRA_OPTS}${CEND}"

pushd / 2>&1 > /dev/null

echo -e "${CCYAN}Creating output directory...${CEND}"
mkdir -p ${DST_DIR}/

echo
echo -e "${CCYAN}Finding matching files...${CEND}"
echo -e "${CCYAN}Command: ${CWHITE}find $WRK_DIR \\"
echo -e "         ${PATTERNS} \\"
echo -e "         > ${DST_DIR}/${NAME_FILE}${CEND}"
if [ "${VERBOSE}" == "" ]; then
	echo "${PATTERNS}" | xargs find $WRK_DIR > "${DST_DIR}/${NAME_FILE}" 2> /dev/null
else
	echo "${PATTERNS}" | xargs find $WRK_DIR > "${DST_DIR}/${NAME_FILE}"
fi

echo
echo -e "${CCYAN}Indexing...${CEND}"
echo -e "${CCYAN}Command: ${CWHITE}cscope -i ${DST_DIR}/${NAME_FILE} \\"
echo -e "         -f ${DST_DIR}/${CYEINDEX_FILE} \\"
echo -e "         -b ${EXTRA_OPTS}${CEND}"
if [ "${VERBOSE}" == "" ]; then
	cscope -i ${DST_DIR}/${NAME_FILE} -f ${DST_DIR}/${INDEX_FILE} -b ${EXTRA_OPTS} 2> /dev/null
else
	cscope -v -i ${DST_DIR}/${NAME_FILE} -f ${DST_DIR}/${INDEX_FILE} -b ${EXTRA_OPTS}
fi

popd 2>&1 > /dev/null

echo -e "${CWHITE}Done!${CEND}"

